#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2016 Mobicage NV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @@license_version:1.1@@

# WARNING: this is a generated file - DO NOT MODIFY

import logging

__all__ = [ 'localize', 'SUPPORTED_LANGUAGES' ]

DEFAULT_LANGUAGE = "en"

def localize(lang, key, **kwargs):
    if not lang:
        lang = DEFAULT_LANGUAGE
    lang = lang.replace('-', '_')
    if lang not in D:
        if '_' in lang:
            lang = lang.split('_')[0]
            if lang not in D:
                lang = DEFAULT_LANGUAGE
        else:
            lang = DEFAULT_LANGUAGE
    langdict = D[lang]
    if key not in langdict:
        # Fall back to default language
        if lang != DEFAULT_LANGUAGE:
            logging.warn("Translation key %s not found in language %s - fallback to default" % (key, lang))
            lang = DEFAULT_LANGUAGE
            langdict = D[lang]
    if key in langdict:
        return langdict[key] % kwargs
    logging.warn("Translation key %s not found in default language. Fallback to key" % key)
    return unicode(key) % kwargs

D = { }

# Generated by Mobitrans at Tue Mar 15 10:13:19 2016


# ###########################################################################################

D["en"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s has %(count)d new messages for you""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s has 1 new message for you""",


"""%(app_name)s mobile registration""": u"""%(app_name)s mobile registration""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s added a personal note:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s declined your request to track his/her location.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s does not have a device which supports location tracking.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s invites you to the %(app_name)s app!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s just joined %(app_name)s, and we found you in his/her Facebook friends list.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s added a personal note:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Hello,

We just welcomed you in our company.
Did you know we also offer our services through the %(app_name)s app?
Click the \"Add to this app\" button to add us to your services list.

Kind regards,
%(service_name)s.""",


"""_enable_location_services_ios7""": u"""To turn on location services:
1. Leave the %(app_name)s app and go to the Settings app
2. Tap Privacy > Location Services
3. Search for %(app_name)s and toggle the switch to ON""",


"""_enable_location_services_ios8""": u"""To turn on location services:
1. Leave the %(app_name)s app and go to the Settings app
2. Tap Privacy > Location Services
3. Search for %(app_name)s, tap on %(app_name)s and set location access to 'Always'""",


"""_friend_denied_location_services""": u"""%(name)s has disabled location services for the %(app_name)s app""",


"""_friendship_accepted""": u"""Hello %(name)s,
%(friend_name)s is now connected to you.""",


"""_friendship_established""": u"""Hello %(name)s,
You are now friends with %(friend_name)s.""",


"""_friendship_request_failed""": u"""Hi %(name)s,
Your connection request with %(friend_name)s failed.
Press the invite button to invite %(friend_name)s.""",


"""_invited_too_often""": u"""Hello %(name)s,
You invited %(friend_email)s 3 times.
To prevent spam, %(app_name)s will not send any more invitations.""",


"""_invited_too_often_this_week""": u"""Hello %(name)s,
You already invited %(friend_email)s earlier this week.
To prevent spam, %(app_name)s will not send any more invitations.""",


"""_invited_yourself""": u"""Hello %(name)s,
You tried to become friends with yourself.
Unfortunately this is not possible.""",


"""_invitee_was_already_friend""": u"""Hello %(name)s,
You tried to invite %(friend_email)s who is already in your friend list.""",


"""_location_services_denied""": u"""%(name)s requested your location, but you have disabled location services for the %(app_name)s app.""",


"""_unsupported_attachment_file_type""": u"""Unsupported file type for attachment %(url)s
We only support pdf, jpeg and png files""",


"""_welcome_msg""": u"""Welcome to the %(app_name)s app!

Connect to your favorite suppliers, associations, care institutions and friends and start communicating.

Happy messaging!

PS: If you want to participate in the %(app_name)s app, contact %(contact_email_address)s""",


"""Accept invitation""": u"""Accept invitation""",


"""account_already_deactivated""": u"""You are not subscribed (anymore) to the %(app_name)s app with this account (%(account)s).""",


"""account_already_disconnected_from_service""": u"""You are not subscribed (anymore) to %(service_name)s.""",


"""Add to my services""": u"""Add to my services""",


"""Address""": u"""Address""",


"""An unknown error has occurred""": u"""An unknown error has occurred""",


"""Associations""": u"""Associations""",


"""broadcast_reminder_explanation""": u"""You receive this notification because you are subscribed to: %(broadcast_type)s""",


"""Can not connect to server""": u"""Can not connect to server""",


"""Cancel""": u"""Cancel""",


"""Care""": u"""Care""",


"""cause_1""": u"""Cause one""",


"""cause_2""": u"""Cause two""",


"""cause_3""": u"""Cause three""",


"""cause_4""": u"""Cause four""",


"""Community Services""": u"""Community Services""",


"""Could not determine file type for attachment %(url)s""": u"""Could not determine file type for attachment %(url)s""",


"""Could not download attachment %(url)s""": u"""Could not download attachment %(url)s""",


"""dear_name""": u"""Dear %(name)s""",


"""Decline invitation""": u"""Decline invitation""",


"""Discover our new app""": u"""Discover our app""",


"""Distance: %(distance)s km""": u"""Distance: %(distance)s km""",


"""E-mail address""": u"""E-mail address""",


"""eID data""": u"""eID data""",


"""email_reminder_cause_force_quitted""": u"""You forcibly quit the %(app_name)s app and have not opened it since then. You do not have to forcibly quit applications on your smartphone. Doing so does not affect the battery lifetime of your smartphone. Forcibly quitting the %(app_name)s app causes that messaging can not be delivered into the app anymore, until you open it again.""",


"""email_reminder_cause_no_internet""": u"""You could not connect to the Internet with your smartphone in the last 2 days. To resolve this, you can connect to mobile Internet or a WiFi network in the neighborhood.""",


"""email_reminder_cause_no_push""": u"""You have chosen to not receive push notifications from the %(app_name)s app. We can not deliver messages to you if you disabled push notifications. You can enable push notifications for the %(app_name)s app in the settings of your smartphone.""",


"""email_reminder_cause_uninstalled""": u"""You (accidently) deleted the %(app_name)s app. If you deleted the app, then you can install it again via the %(app_store)s or %(google_play)s and register as %(account)s. If you deleted the app and you do not want to receive any messages, then you can unsubscribe at the bottom of this e-mail.""",


"""email_reminder_intro""": u"""It has come to our attention that a number of messages in the %(app_name)s app could not reach you for some reason. This means that we could not deliver the messages on your smartphone. This can have a number of causes:""",


"""email_reminder_intro_no_mobile_html""": u"""It has come to our attention that you have received a number of messages in the %(app_name)s app. You can view these messages by installing the %(app_name)s app on your smartphone and register with your e-mail. The %(app_name)s app can be downloaded from the App Store or Google Play. If you have any further questions you can always contact %(support)s or take a look at our <a href=\"%(website_link)s\">website</a>.""",


"""email_reminder_intro_no_mobile_text""": u"""It has come to our attention that you have received a number of messages in the %(app_name)s app. You can view these messages by installing the %(app_name)s app on your smartphone and register with your e-mail. The %(app_name)s app can be downloaded from the App Store or Google Play. If you have any further questions you can always contact %(support)s or take a look at our website: %(website_link)s.""",


"""email_reminder_message_summary""": u"""Message summary""",


"""email_reminder_outro_part1""": u"""We hope all potential problems have been solved and the inconvenience is limited to a minimum. Furthermore, we wish you a lot of fun using the %(app_name)s app!""",


"""email_reminder_outro_part2_html""": u"""If you have any further questions you can always contact %(support)s or take a look at our <a href=\"%(website_link)s\">website</a>.""",


"""email_reminder_outro_part2_text""": u"""If you have any further questions you can always contact %(support)s or take a look at our website: %(website_link)s.""",


"""email_reminder_unsubscribe_caption""": u"""Unsubscribe from \"%(notification_type)s\" of %(service)s""",


"""email_reminder_unsubscribe_from_email_html""": u"""If you prefer not to receive this email anymore, then you can <a href=\"%(unsubscribe_link)s\">unsubscribe here</a>.""",


"""email_reminder_unsubscribe_from_email_text""": u"""If you prefer not to receive this email anymore, then you can unsubscribe using the link below.""",


"""Enter your reply:""": u"""Enter your reply:""",


"""Error""": u"""Error""",


"""Failed to unregister""": u"""Failed to unregister""",


"""Failed to upload the photo to %(service_name)s""": u"""Failed to upload the photo to %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Flow result of %(user)s for %(flow)s""",


"""http://www.ourcityapps.com""": u"""http://www.ourcityapps.com""",


"""Install %(other_app_name)s""": u"""Install %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Invalid download_url (%(url)s). It must be reachable over http or https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Invite %(name)s to connect on %(app_name)s""",


"""Invite %(name)s""": u"""Invite %(name)s""",


"""Kind regards""": u"""Kind regards""",


"""Location: %(address)s""": u"""Location: %(address)s.""",


"""mdp_missing_address""": u"""The address stored in your MIDIGIPASS account is incomplete. Please configure your address in MYDIGIPASS and try again.""",


"""mdp_missing_eid_data""": u"""There is no eID data stored in your MIDIGIPASS account. Please configure your eID data in MYDIGIPASS and try again.""",


"""mdp_missing_email""": u"""There is no e-mail address stored in your MIDIGIPASS account. Please configure your e-mail address in MYDIGIPASS and try again.""",


"""mdp_missing_phone""": u"""There is no phone number stored in your MIDIGIPASS account. Please configure your phone number in MYDIGIPASS and try again.""",


"""mdp_missing_profile""": u"""The personal information stored in your MIDIGIPASS account is incomplete. Please complete your profile in MYDIGIPASS and try again.""",


"""mdp_missing_scopes""": u"""There is insufficient data available in your MYDIGIPASS account. The following data is missing: %(missing_data)s

Please complete your MYDIGIPASS account data and try again.

Also make sure you have the latest version of the \"MYDIGIPASS Authenticator for Mobile\" app.""",


"""Merchants""": u"""Merchants""",


"""My services""": u"""My services""",


"""Nearby services""": u"""Nearby services""",


"""No matching service found""": u"""No matching service found.""",


"""No service found""": u"""No service found.""",


"""notify_service_location_tracking""": u"""%(service)s is tracking your location until %(until)s.""",


"""Phone number""": u"""Phone number""",


"""Please try again later.""": u"""Please try again later.""",


"""Profile""": u"""Profile""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Received location of %(name)s.

Accuracy: %(accuracy)sm""",


"""Reply""": u"""Reply""",


"""Save""": u"""Save""",


"""Scan QR code to discover!""": u"""Scan QR code to discover!""",


"""Search results""": u"""Search results""",


"""Send reply""": u"""Send reply""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Service %(name)s wants to connect to you via %(app_name)s.""",


"""Services""": u"""Services""",


"""Show map""": u"""Show map""",


"""Spaces are not allowed in an e-mail address""": u"""Spaces are not allowed in an e-mail address""",


"""Submit""": u"""Submit""",


"""successfully_unsubscribed_broadcast_type""": u"""You have been successfully unsubscribed from notifications with type \"%(notification_type)s\" of %(service)s.""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""The scanned QR code is not supported by the %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">%(app_name)s support</a>""",


"""the_app_team""": u"""The %(app_name)s Team""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_coach_email_address_html""": u"""the <a href=\"mailto:%(email)s\">Our City Coach</a>""",


"""the_our_city_app_team""": u"""The Our City App Team""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""",


"""Unsubscribe""": u"""Unsubscribe""",


"""User %(name)s has requested to share your location.""": u"""User %(name)s has requested to share your location.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s wants to get in touch with you via %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""We could not determine the location of %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Which type of broadcasts do you wish to receive?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""Why do you wish to unsubscribe to this e-mail?""",


"""You are already connected with %(name)s.""": u"""You are already connected with %(name)s.""",


"""You are now unsubscribed.""": u"""You are now unsubscribed.""",


"""You can not register with this e-mail address""": u"""You can not register with this e-mail address"""}


# ###########################################################################################

D["es"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s tiene %(count)d mensajes nuevos para ti""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s tiene 1 mensaje nuevo para ti""",


"""%(app_name)s mobile registration""": u"""Registro %(app_name)s""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s ha aceptado su petición para compartir ubicación.
Información actualizada:

Precisión: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s ha aceptado su petición para compartir su ubicación. Desafortunadamente, no se puede establecer su ubicación en este momento.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s ha añadido una nota personal:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s ha rechazado su petición para establecer su ubicación.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s no dispone de un dispositivo con soporte para localización geográfica.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s le ha invitado a la app %(app_name)s!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s se ha unido a %(app_name)s. Le hemos localizado a usted en la lista d contactos de Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s ha añadido una nota personal:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s le recomienda conectarse a %(service_name)s en %(app_name)s.

Acerca de %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s le recomienda conectarse a %(service_name)s en %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Hola,
Acabamos de bienvenida a nuestra empresa.
¿Sabías que también ofrecemos nuestros servicios a través de la aplicación de %(app_name)s?
Haga clic en el botón \"Añadir a isso app\" para añadirnos a su lista de servicios.
Un cordial saludo, %(service_name)s.""",


"""_enable_location_services_ios7""": u"""Para activar Localización:
1. Deje el %(app_name)s app e abra el Ajustes app
2. Pulse en Privacidad  > Localización
3. Búsqueda de %(app_name)s y alternar el interruptor en ON""",


"""_enable_location_services_ios8""": u"""Para activar Localización:
1. Deje el %(app_name)s app e abra el Ajustes app
2. Pulse en Privacidad  > Localización
3. Búsqueda de %(app_name)s y alternar el acceso a ubicación en 'Siempre'""",


"""_friend_denied_location_services""": u"""%(name)s ha desactivado localización del %(app_name)s app""",


"""_friendship_accepted""": u"""Hola %(name)s,
%(friend_name)s está ahora conectado con usted.
Ya puede gozar de esta experiencia.""",


"""_friendship_established""": u"""Hola %(name)s,
Usted está ahora en contacto con %(friend_name)s.
¡Ya puede gozar de esta experiencia!""",


"""_friendship_request_failed""": u"""Hola %(name)s,
Su petición para conectarse con %(friend_name)s ha fallado.
Presione el botón Invitar para invitar a %(friend_name)s.""",


"""_invited_too_often""": u"""Hola %(name)s,
Ha invitado a %(friend_email)s en tres ocasiones.
Para prevenir el correo Spam, %(app_name)s no enviará más invitaciones a este contacto.""",


"""_invited_too_often_this_week""": u"""Hola %(name)s,
Ya ha invitado a %(friend_email)s anteriormente esta semana.
Para prevenir el correo Spam, %(app_name)s no enviará más invitaciones a este contacto.""",


"""_invited_yourself""": u"""Hola %(name)s,
Ha intentado añadirse como contacto usted mismo.
Lo sentimos, pero esto no es posible.""",


"""_invitee_was_already_friend""": u"""Hola %(name)s,
Ha intentado invitar a %(friend_email)s . Este contacto ya se encuentra en su lista de contactos.""",


"""_location_services_denied""": u"""%(name)s solicitado su ubicación, pero hay localización con discapacidad para el %(app_name)s app.""",


"""_unsupported_attachment_file_type""": u"""Tipo de archivo no admitido para accesorio %(url)s
Sólo apoyamos archivos pdf, jpeg y png""",


"""_welcome_msg""": u"""¡Bienvenido a la App de %(app_name)s!

Agrega en la aplicación a tus asociaciones, servicios, proveedores y tiendas favoritas, conecta con tus amigos para intercambiar mensajes.

Mensajes de feliz!

PS: Si deseas añadir una nueva tienda o servicio propio en la App de %(app_name)s, contacta con %(contact_email_address)s""",


"""Accept invitation""": u"""Aceptar invitación""",


"""account_already_deactivated""": u"""(Ya) No estas suscrito a la app %(app_name)s con esta cuenta (%(account)s).""",


"""account_already_disconnected_from_service""": u"""(Ya) No estas suscrito a %(service_name)s.""",


"""Add to my services""": u"""Añadir a isso app""",


"""Address""": u"""Dirección""",


"""An unknown error has occurred""": u"""Un error desconocido a ocurrido""",


"""Associations""": u"""Asociaciones""",


"""broadcast_reminder_explanation""": u"""Estas recibiendo esta notificación porque estas suscrito a: %(broadcast_type)s'""",


"""Can not connect to server""": u"""No es posible conectar con el servidor""",


"""Cancel""": u"""Cancelar""",


"""Care""": u"""Cuidado""",


"""cause_1""": u"""Causa uno""",


"""cause_2""": u"""Causa dos""",


"""cause_3""": u"""Causa tres""",


"""cause_4""": u"""Causa cuatro""",


"""Community Services""": u"""Servicio a la comunidad""",


"""Could not determine file type for attachment %(url)s""": u"""No pudo determinar el tipo de archivo adjunto %(url)s""",


"""Could not download attachment %(url)s""": u"""No se pudo descargar el adjunto %(url)s""",


"""dear_name""": u"""Estimado %(name)s""",


"""Decline invitation""": u"""Rechazar invitación""",


"""Discover our new app""": u"""Descubre nuestra app""",


"""Distance: %(distance)s km""": u"""Distancia: %(distance)s km""",


"""E-mail address""": u"""Dirección de correo electrónico""",


"""email_reminder_cause_force_quitted""": u"""Forzaste el cierre de la app %(app_name)s y no la has abierto desde entonces. No tienes por qué forzar el cierre de aplicaciones en tu Smartphone. El hacer esto no va a repercutir en el tiempo de vida de la batería de tu Smartphone. Forzar el cierre de la app %(app_name)s provoca que no se reciban los mensajes en la app hasta que se habrá de nuevo.""",


"""email_reminder_cause_no_internet""": u"""No te has podido conectar a internet con tu Smartphone en los últimos dos días. Para solucionar esto, puedes conectarte con datos móviles o a una red WIFI en el vecindario.""",


"""email_reminder_cause_no_push""": u"""Has elegido no recibir notificaciones push de la app %(app_name)s. No podrás recibir mensajes si deshabilitas las notificaciones push. Puedes activar las notificaciones push para la app %(app_name)s en la configuración de tu Smartphone.""",


"""email_reminder_cause_uninstalled""": u"""Borraste (accidentalmente) la app %(app_name)s. Si borraste la aplicación, la puedes instalar de nuevo por medio de la %(app_store)s o %(google_play)s y registrarte cómo %(account)s. Si borraste la aplicación y no deseas recibir mensajes puedes darte de baja en la parte inferior de este correo.""",


"""email_reminder_intro""": u"""Nos ha llamado la atención, que por alguna razón un número de mensajes en la app %(app_name)s no te han llegado. Esto significa que nosotros no pudimos entregar los mensajes en tu Smartphone. Esto tiene posibles causas:""",


"""email_reminder_intro_no_mobile_html""": u"""Ha llegado a nuestra atención que ha recibido una serie de mensajes en la aplicación %(app_name)s. Puede ver estos mensajes mediante la instalación del %(app_name)s aplicación en el teléfono inteligente y registrarse con su dirección de e-mail. El %(app_name)s aplicación se puede descargar desde la App Store o Google Play. Si tiene alguna duda, siempre puede contactar %(support)s, o echar un vistazo a nuestra <a href=\"%(website_link)s\">página web</a>.""",


"""email_reminder_intro_no_mobile_text""": u"""Ha llegado a nuestra atención que ha recibido una serie de mensajes en la aplicación %(app_name)s. Puede ver estos mensajes mediante la instalación del %(app_name)s aplicación en el teléfono inteligente y registrarse con su dirección de e-mail. El %(app_name)s aplicación se puede descargar desde la App Store o Google Play. Si tiene alguna duda, siempre puede contactar %(support)s, o echar un vistazo a nuestra página web: %(website_link)s.""",


"""email_reminder_message_summary""": u"""Resumen de mensaje""",


"""email_reminder_outro_part1""": u"""Esperamos que todos los posibles problemas hayan sido resueltos y las molestias se limiten a lo mí­nimo. Además te deseamos mucha diversión usando la app %(app_name)s!""",


"""email_reminder_outro_part2_html""": u"""Si tienes más preguntas, siempre puedes contactar a %(support)s o echar un vistazo a nuestro <a href=\"%(website_link)s\">sitio web</a>.""",


"""email_reminder_outro_part2_text""": u"""Si tienes alguna otra duda, siempre puedes contactar a %(support)s o echar un vistazo a nuestro sitio web: %(website_link)s.
""",


"""email_reminder_unsubscribe_caption""": u"""Darse de baja de \"%(notification_type)s\" de %(service)s""",


"""email_reminder_unsubscribe_from_email_html""": u"""Si no desea recibir este correo electrónico más, entonces puede <a href=\"%(unsubscribe_link)s\">de baja aquí</a>.""",


"""email_reminder_unsubscribe_from_email_text""": u"""Si no desea recibir este correo electrónico más, entonces puede darse de baja mediante el siguiente enlace.""",


"""Enter your reply:""": u"""Introduzca su respuesta:""",


"""Error""": u"""Error""",


"""Failed to unregister""": u"""Error al anular el registro""",


"""Failed to upload the photo to %(service_name)s""": u"""Error al cargar la foto en %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Resultado de Flujo %(user)s para %(flow)s""",


"""http://www.ourcityapps.com""": u"""http://www.ourcityapp.es""",


"""Install %(other_app_name)s""": u"""Instalar %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hiperenlace inválido (%(url)s). Debe ser accesible por http o https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Invitar a %(name)s a conectarse con %(app_name)s""",


"""Invite %(name)s""": u"""Invitar a %(name)s""",


"""Kind regards""": u"""Saludos cordiales""",


"""Location: %(address)s""": u"""Ubicación: %(address)s.""",


"""mdp_missing_address""": u"""La dirección almacenada en su cuenta MIDIGIPASS es incompleta. Por favor, configure su dirección en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_eid_data""": u"""No hay datos de identificación electrónica almacenados en su cuenta MIDIGIPASS. Por favor, configure sus datos de identificación electrónica en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_email""": u"""No hay una dirección de correo electrónico almacenado en su cuenta MIDIGIPASS. Por favor, configure su dirección de e-mail en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_phone""": u"""No hay un número de teléfono almacenado en su cuenta MIDIGIPASS. Por favor, configure su número de teléfono en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_profile""": u"""La información personal almacenada en su cuenta MIDIGIPASS es incompleta. Por favor completar su perfil en MYDIGIPASS y vuelve a intentarlo.""",


"""Merchants""": u"""Comerciantes""",


"""My services""": u"""Mis servicios""",


"""Nearby services""": u"""Servicios cercanos""",


"""No matching service found""": u"""No se encontraron resultados.""",


"""No service found""": u"""No se encontraron resultados.""",


"""notify_service_location_tracking""": u"""%(service)s es el seguimiento de su ubicación hasta las %(until)s.""",


"""Phone number""": u"""Número de teléfono""",


"""Please try again later.""": u"""Inténtelo de nuevo más tarde.""",


"""Profile""": u"""Perfil""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Se ha recibido la ubicación de %(name)s.

Precisión: %(accuracy)sm""",


"""Reply""": u"""Responder""",


"""Save""": u"""Guardar""",


"""Scan QR code to discover!""": u"""Escanear un código QR para buscar!""",


"""Search results""": u"""Resultados de la búsqueda""",


"""Send reply""": u"""Envíe respuesta""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Service %(name)s desea conectarse con usted a través de %(app_name)s.""",


"""Services""": u"""Servicios""",


"""Show map""": u"""Mostrar mapa""",


"""Spaces are not allowed in an e-mail address""": u"""No se permiten espacios en una dirección de correo electrónico""",


"""Submit""": u"""Enviar""",


"""successfully_unsubscribed_broadcast_type""": u"""Has sido dado de baja exitosamente de las notificaciones del tipo \"%(notification_type)s\" de %(service)s.""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""El código QR ​​escaneado no está soportado por el %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">Soporte de %(app_name)s</a>""",


"""the_app_team""": u"""El equipo de %(app_name)s""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_coach_email_address_html""": u"""El <a href=\"mailto:%(email)s\">entrenador de Our City</a>""",


"""the_our_city_app_team""": u"""El equipo de Our City App""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""No hay dirección de correo electrónico configurado en su cuenta de Facebook. Por favor, inicie sesion con su correo electrónico.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Este servicio no es compatible con el %(current_app_name)s app. Por favor, instalar el %(other_app_name)s app.""",


"""Unsubscribe""": u"""Darse de baja""",


"""User %(name)s has requested to share your location.""": u"""User %(name)s ha solicitado compartir su ubicación.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s desea contactar con usted a través de %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""No se puede establecer la ubicación de %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""¿Qué tipo de transmisiones desea recibir?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""¿Por qué desea cancelar su suscripción a este e-mail?""",


"""You are already connected with %(name)s.""": u"""Usted ya está conectado con %(name)s.""",


"""You are now unsubscribed.""": u"""Ahora está de baja.""",


"""You can not register with this e-mail address""": u"""No se puede registrar con esta dirección de correo electrónico"""}


# ###########################################################################################

D["fr"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s a %(count)d de nouveaux messages pour vous""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s a 1 nouveau message pour vous""",


"""%(app_name)s mobile registration""": u"""Votre inscription %(app_name)s""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s partage désormais sa position avec vous.
Information récente:

Précision: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s a accepté votre requête pour partager sa position. Malheureusement, nous ne pouvons pas déterminer sa position en ce moment.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s a ajouté un message personnel:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s a refusé votre requête.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s n'a pas un appareil portable qui peut donner la position.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s vous invite à utiliser l'application %(app_name)s!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s a rejoint %(app_name)s, et on vous a trouvé dans ses amis Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s a ajouté un message personnel:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s vous recommande d'utiliser le service %(service_name)s avec %(app_name)s.

Info sur %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s vous recommande d'utiliser le service %(service_name)s avec %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Bonjour,
Nous venons d'avoir la joie de vous accueillir dans notre société.
Saviez-vous que vous pouvez aussi accéder à nos services via l'application %(app_name)s ?
Cliquez sur le bouton \"Ajouter à cette application\" pour nous ajouter à votre liste de services.
Sincères salutations, %(service_name)s.""",


"""_enable_location_services_ios7""": u"""Pour activer le service de localisation:
1. Laissez le %(app_name)s app et allez dans les Réglages
2. Allez dans Confidentialité > Service de localisation
3. Recherchez %(app_name)s et basculez l'interrupteur sur ON""",


"""_enable_location_services_ios8""": u"""Pour activer le service de localisation:
1. Laissez le %(app_name)s app et allez dans les Réglages
2. Allez dans Confidentialité > Service de localisation
3. Recherchez %(app_name)s et modifiez l'accès à votre position sur «Toujours»""",


"""_friend_denied_location_services""": u"""%(name)s a désactivé le service de localisation pour l'application %(app_name)s""",


"""_friendship_accepted""": u"""Bonjour %(name)s,
%(friend_name)s est désormais connecté à vous.
Joyeux messages  !""",


"""_friendship_established""": u"""Bonjour %(name)s,
Maintenant vous êtes amis avec %(friend_name)s.
Joyeux messages!""",


"""_friendship_request_failed""": u"""Bonjour %(name)s,
Votre demande de connexion avec %(friend_name)s a échoué.
Appuyez à nouveau sur le bouton pour inviter %(friend_name)s.""",


"""_invited_too_often""": u"""Bonjour %(name)s,
Vous avez invité %(friend_email)s 3 fois.
Pour éviter les spams, %(app_name)s ne vous enverra plus d'invitations.""",


"""_invited_too_often_this_week""": u"""Cher %(name)s,
Vous avez déjà invité %(friend_email)s durant cette semaine.
Pour éviter les spams, %(app_name)s ne va plus envoyer des invitations à %(friend_email)s.
""",


"""_invited_yourself""": u"""Bonjour %(name)s,
Vous avez essayé de devenir ami avec vous-même.
Malheureusement ce n'est pas possible.""",


"""_invitee_was_already_friend""": u"""Bonjour %(name)s,
Vous avez invité %(friend_email)s qui est déjà dans votre liste d'amis.""",


"""_location_services_denied""": u"""%(name)s a demandé votre position, mais vous avez désactivé le service de localisation pour l'application %(app_name)s.""",


"""_unsupported_attachment_file_type""": u"""Le fichier %(url)s n'est pas pris en charge.
Sont supportés les formats pdf, jpeg et png""",


"""_welcome_msg""": u"""Bienvenue dans %(app_name)s!

Ajoutez vos commerçants et associations préférés et échangez avec les autres habitants.

Profitez-en!

PS: Si vous voulez ajouter votre propre application à %(app_name)s, contacter %(contact_email_address)s""",


"""Accept invitation""": u"""Accepter l'invitation""",


"""account_already_deactivated""": u"""Vous n'êtes pas abonné (plus) à l'application de %(app_name)s avec ce compte (%(account)s).""",


"""account_already_disconnected_from_service""": u"""Vous n'êtes pas abonné (plus) pour %(service_name)s.""",


"""Add to my services""": u"""Ajouter à cette application""",


"""Address""": u"""Adresse""",


"""An unknown error has occurred""": u"""Une erreur inconnue s'est produite""",


"""Associations""": u"""Associations""",


"""broadcast_reminder_explanation""": u"""Vous recevez cette notification, car vous êtes abonné à: %(broadcast_type)s""",


"""Can not connect to server""": u"""Impossible de se connecter au serveur""",


"""Cancel""": u"""Annuler""",


"""Care""": u"""Soins""",


"""cause_1""": u"""Cause un""",


"""cause_2""": u"""Cause deux""",


"""cause_3""": u"""Cause trois""",


"""cause_4""": u"""Cause quatre""",


"""Community Services""": u"""Services Publics""",


"""Could not determine file type for attachment %(url)s""": u"""Impossible de déterminer le type de fichier pour l'attachement %(url)s""",


"""Could not download attachment %(url)s""": u"""Impossible de télécharger l'attachement %(url)s""",


"""dear_name""": u"""Cher %(name)s""",


"""Decline invitation""": u"""Refuser l'invitation""",


"""Discover our new app""": u"""Découvrez notre application""",


"""Distance: %(distance)s km""": u"""Distance: %(distance)s km""",


"""E-mail address""": u"""Adresse e-mail""",


"""eID data""": u"""Données eID""",


"""email_reminder_cause_force_quitted""": u"""Vous avez choisi de forcer l'arrêt de l'application de %(app_name)s et ne l'avez pas ouverte depuis. Vous ne devez pas forcer l'arrêt des applications sur votre smartphone. Cela n'a aucune incidence sur la durée de vie de la batterie de votre smartphone. Quitter de force l'application %(app_name)s provoque que les messages ne peuvent plus être délivrés dans l'application jusqu'à ce que vous l'ouvriez à nouveau.""",


"""email_reminder_cause_no_internet""": u"""Vous n'avez pas pu vous connecter à Internet avec votre smartphone durant les 2 derniers jours. Pour résoudre ce problème, vous pouvez vous connecter à l'Internet mobile ou à un réseau WiFi dans le quartier.""",


"""email_reminder_cause_no_push""": u"""Vous avez choisi de ne pas recevoir les notifications push de l'application de %(app_name)s. Nous ne pouvons pas vous délivrer des messages si vous avez désactivé les notifications push. Vous pouvez activer les notifications push pour l'application de %(app_name)s dans les paramètres de votre smartphone.""",


"""email_reminder_cause_uninstalled""": u"""Vous (accidentellement) avez supprimé l'application de %(app_name)s. Si vous avez supprimé l'application, vous pouvez l'installer à nouveau via le %(app_store)s ou %(google_play)s et enregistrez en tant %(account)s. Si vous avez supprimé l'application et vous ne voulez pas recevoir de messages, alors vous pouvez vous désinscrire en bas de cet e-mail.""",


"""email_reminder_intro""": u"""Il a été porté à notre attention qu'un certain nombre de messages dans l'application de %(app_name)s n'ont pas pu être reçus par vous pour une raison quelconque. Ceci signifie que nous ne pouvions pas livrer les messages sur votre smartphone. Ceci peut avoir un certain nombre de causes:""",


"""email_reminder_intro_no_mobile_html""": u"""Notre attention a été attirée par le fait que vous avez reçu un certain nombre de messages dans l'application de %(app_name)s. Vous pouvez afficher ces messages en installant l'application %(app_name)s sur votre smartphone et vous inscrire avec votre adresse e-mail. L'application de %(app_name)s peut être téléchargé à partir de l'App Store ou Google Play. Si vous avez d'autres questions, vous pouvez toujours contacter %(support)s ou jeter un oeil à notre <a href=\"%(website_link)s\">site</a> .""",


"""email_reminder_intro_no_mobile_text""": u"""Notre attention a été attirée par le fait que vous avez reçu un certain nombre de messages dans l'application de %(app_name)s. Vous pouvez afficher ces messages en installant l'application %(app_name)s sur votre smartphone et vous inscrire avec votre adresse e-mail. L'application de %(app_name)s peut être téléchargé à partir de l'App Store ou Google Play. Si vous avez d'autres questions, vous pouvez toujours contacter %(support)s ou jeter un oeil à notre site Web: %(website_link)s.""",


"""email_reminder_message_summary""": u"""Résumé du message""",


"""email_reminder_outro_part1""": u"""Nous espérons que tous les problèmes potentiels ont été résolus et que l'inconvénient a été limité au minimum. En outre, nous vous souhaitons beaucoup de plaisir en utilisant l'application %(app_name)s!""",


"""email_reminder_outro_part2_html""": u"""Si vous avez d'autres questions, vous pouvez toujours contacter %(support)s ou visiter notre <a href=\"%(website_link)s\">site web</a> .""",


"""email_reminder_outro_part2_text""": u"""Si vous avez d'autres questions, vous pouvez toujours contacter %(support)s ou visiter notre site web: %(website_link)s.""",


"""email_reminder_unsubscribe_caption""": u"""Se désabonner de \"%(notification_type)s\" de %(service)s""",


"""email_reminder_unsubscribe_from_email_html""": u"""Si vous préférez ne plus recevoir cet e-mail , alors vous pouvez <a href=\"%(unsubscribe_link)s\">vous désabonner ici</a> .""",


"""email_reminder_unsubscribe_from_email_text""": u"""Si vous préférez ne plus recevoir cet e-mail, alors vous pouvez vous désinscrire en utilisant le lien ci-dessous.""",


"""Enter your reply:""": u"""Entrez votre réponse:""",


"""Error""": u"""Erreur""",


"""Failed to unregister""": u"""Impossible d'annuler l'inscription""",


"""Failed to upload the photo to %(service_name)s""": u"""Impossible de télécharger la photo vers %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Résultat du flux de %(user)s des %(flow)s""",


"""http://www.ourcityapps.com""": u"""http://www.villeconnectee.com""",


"""Install %(other_app_name)s""": u"""Installez %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hyperlink invalide (%(url)s). Il doit être accessible via http ou https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Inviter %(name)s à se connecter à %(app_name)s""",


"""Invite %(name)s""": u"""Inviter %(name)s""",


"""Kind regards""": u"""Bien Cordialement""",


"""Location: %(address)s""": u"""La position: %(address)s.""",


"""mdp_missing_address""": u"""L'adresse configurée dans votre compte MYDIGIPASS est incomplète. S'il vous plaît configurez votre adresse à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_eid_data""": u"""Il n'y a pas de données d'identité électroniques configurées dans votre compte NYDIGIPASS. S'il vous plaît configurer vos données eID dans un MYDIGIPASS essayer à nouveau.""",


"""mdp_missing_email""": u"""Il n'y a aucune adresse email configurée dans votre compte MIDIGIPASS. S'il vous plaît configurez votre adresse e-mail à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_phone""": u"""Il n'y a aucun numéro de téléphone configurée dans votre compte MYDIGIPASS. S'il vous plaît configurez votre numéro de téléphone à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_profile""": u"""Les infomations personnelles configurées dans votre compte MYDIGIPASS sont incomplètes. S'il vous plaît configurez votre profil à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_scopes""": u"""Il n'y a pas suffisamment de données disponibles dans votre compte MYDIGIPASS. Les données suivantes manquent: %(missing_data)s

S'il vous plaît remplir vos données de compte MYDIGIPASS et essayez à nouveau.

Assurez-vous également que vous avez la dernière version de l'application \"MYDIGIPASS Authenticator for mobile\".""",


"""Merchants""": u"""Marchands""",


"""My services""": u"""Mes services""",


"""Nearby services""": u"""Services dans votre quartier""",


"""No matching service found""": u"""Pas de résultats.""",


"""No service found""": u"""Pas de résultats.""",


"""notify_service_location_tracking""": u"""%(service)s suit votre position jusqu'à %(until)s.""",


"""Phone number""": u"""Numéro de téléphone""",


"""Please try again later.""": u"""Prière de recommencer plus tard.""",


"""Profile""": u"""Profil""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""La position de %(name)s a été reçue.

Exactitude: %(accuracy)sm""",


"""Reply""": u"""Répondre""",


"""Save""": u"""Sauvegarder""",


"""Scan QR code to discover!""": u"""Scanner un code QR pour découvrir!""",


"""Search results""": u"""Résultats de la recherche""",


"""Send reply""": u"""Envoyer la réponse""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Service %(name)s veut se connecter à vous via %(app_name)s.""",


"""Services""": u"""Services""",


"""Show map""": u"""Ouvrir la carte""",


"""Spaces are not allowed in an e-mail address""": u"""Les espaces ne sont pas autorisés dans une adresse e-mail""",


"""Submit""": u"""Envoyer""",


"""successfully_unsubscribed_broadcast_type""": u"""Vous avez été désabonné des notifications de type «%(notification_type)s» de %(service)s.""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""Le code QR numérisé n'est pas supporté par l'app de %(app_name)s""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">soutien %(app_name)s</a>""",


"""the_app_team""": u"""L'équipe de %(app_name)s""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_coach_email_address_html""": u"""le <a href=\"mailto:%(email)s\">Coach de Ville Connectée</a>""",


"""the_our_city_app_team""": u"""L'équipe Ville Connectée""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Il n'y a aucune adresse email configurée dans votre compte facebook ou vous n'avez pas donné les autorisations pour accéder à votre email. Merci de choisir la connexion via email.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Ce service n'est pas supporté par l'app de %(current_app_name)s.  S'il vous plaît installez l'app %(other_app_name)s app.""",


"""Unsubscribe""": u"""Désinscrire""",


"""User %(name)s has requested to share your location.""": u"""%(name)s a envoyé une demande pour que vous partagiez votre position.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s veut communiquer avec vous via %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""Nous n'avons pas pu déterminer la position de %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Quel type de médias souhaitez-vous recevoir?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""Pourquoi voulez-vous vous désabonner à cet e-mail?""",


"""You are already connected with %(name)s.""": u"""Vous êtes déjà connecté avec %(name)s.""",


"""You are now unsubscribed.""": u"""Vous êtes maintenant désinscrit.""",


"""You can not register with this e-mail address""": u"""Vous ne pouvez pas vous inscrire à cette adresse e-mail"""}


# ###########################################################################################

D["nl"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s heeft %(count)d nieuwe berichten voor u""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s heeft 1 nieuw bericht voor u""",


"""%(app_name)s mobile registration""": u"""%(app_name)s mobiele registratie""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s deelt vanaf nu zijn locatie met jou.
Meest recente informatie:

Nauwkeurigheid: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s deelt vanaf nu zijn/haar locatie met jou.
Helaas konden we zijn/haar locatie nu niet bepalen.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s heeft een persoonlijke boodschap toegevoegd:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s heeft je verzoek geweigerd om zijn/haar locatie te bepalen.""",


"""%(name)s does not have a device which supports location tracking.""": u"""Plaatsbepaling is niet ondersteund op het toestel van %(name)s.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s nodigt u uit in de %(app_name)s app!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s gebruikt nu ook %(app_name)s, en we vonden u tussen zijn/haar Facebook vrienden.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s heeft een persoonlijke boodschap toegevoegd:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s beveelt je de dienst %(service_name)s aan op %(app_name)s.

Over %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s beveelt je de smartphone dienst %(service_name)s aan op %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Hallo,

We heten je welkom in onze zaak.
Wist je dat wij ook diensten via de %(app_name)s app aanbieden?
Klik op de \"Voeg toe aan deze app\" knop om ons toe te voegen aan jouw lijst met diensten.

Met vriendelijke groeten,
%(service_name)s""",


"""_enable_location_services_ios7""": u"""Om locatievoorzieningen in te schakelen:
1. Verlaat de %(app_name)s app en ga naar de Instellingen app
2. Tik op Privacy > locatievoorzieningen
3. Zoek naar %(app_name)s en zet de schakelaar aan""",


"""_enable_location_services_ios8""": u"""Om locatievoorzieningen in te schakelen:
1. Verlaat de %(app_name)s app en ga naar de Instellingen app
2. Tik op Privacy > locatievoorzieningen
3. Zoek naar %(app_name)s en zet toegang tot locatie op 'Altijd'""",


"""_friend_denied_location_services""": u"""%(name)s heeft locatievoorzieningen uitgeschakeld voor de %(app_name)s app""",


"""_friendship_accepted""": u"""Beste %(name)s,
Je bent vanaf nu bevriend met %(friend_name)s.""",


"""_friendship_established""": u"""Beste %(name)s,
Je ben vanaf nu bevriend met %(friend_name)s.""",


"""_friendship_request_failed""": u"""Beste %(name)s,
Je verzoek om met %(friend_name)s te communiceren, is mislukt.
Druk op de knop om het opnieuw te proberen.""",


"""_invited_too_often""": u"""Beste %(name)s,
Je hebt %(friend_email)s 3 keer een vriendschapsverzoek gestuurd.
Om spam te vermijden zal %(app_name)s geen bijkomende uitnodigingen versturen.""",


"""_invited_too_often_this_week""": u"""Beste %(name)s,
Je hebt eerder deze week %(friend_email)s al eens een vriendschapsverzoek gestuurd.
Om spam te vermijden zal %(app_name)s geen bijkomende uitnodigingen versturen.""",


"""_invited_yourself""": u"""Beste %(name)s,
Je probeerde een vriendschapsverzoek naar jezelf te versturen.
Dat wordt niet ondersteund.""",


"""_invitee_was_already_friend""": u"""Beste %(name)s,
Je probeerde een vriendschapsverzoek te versturen naar %(friend_email)s waarmee je al bevriend bent.""",


"""_location_services_denied""": u"""%(name)s heeft jouw locatie opgevraagd, maar je hebt locatievoorzieningen uitgeschakeld voor de %(app_name)s app.""",


"""_unsupported_attachment_file_type""": u"""Niet ondersteund bestandstype voor bijlage %(url)s
Wij ondersteunen enkel pdf, jpeg en png bestanden""",


"""_welcome_msg""": u"""Welkom bij de %(app_name)s app!

Voeg de apps van je favoriete winkels en verenigingen toe, connecteer met je vrienden en stuur berichten.
  
Veel succes!

PS: Als je zelf een app wil toevoegen in de %(app_name)s app, neem contact op met %(contact_email_address)s""",


"""Accept invitation""": u"""Verzoek aanvaarden""",


"""account_already_deactivated""": u"""U bent niet (meer) ingeschreven op de %(app_name)s met dit account (%(account)s).""",


"""account_already_disconnected_from_service""": u"""U bent niet (meer) ingeschreven op %(service_name)s.""",


"""Add to my services""": u"""Voeg toe aan deze app""",


"""Address""": u"""Adres""",


"""An unknown error has occurred""": u"""Er is een onbekende fout opgetreden""",


"""Associations""": u"""Verenigingen""",


"""broadcast_reminder_explanation""": u"""U ontvangt deze notificatie omdat u bent ingeschreven op: %(broadcast_type)s""",


"""Can not connect to server""": u"""Kan geen connectie maken met de server""",


"""Cancel""": u"""Annuleren""",


"""Care""": u"""Zorg""",


"""cause_1""": u"""Oorzaak één""",


"""cause_2""": u"""Oorzaak twee""",


"""cause_3""": u"""Oorzaak drie""",


"""cause_4""": u"""Oorzaak vier""",


"""Community Services""": u"""Gemeente diensten""",


"""Could not determine file type for attachment %(url)s""": u"""Kan bestandstype niet bepalen voor bijlage %(url)s""",


"""Could not download attachment %(url)s""": u"""Kan bijlage niet downloaden %(url)s""",


"""dear_name""": u"""Beste %(name)s""",


"""Decline invitation""": u"""Verzoek weigeren""",


"""Discover our new app""": u"""Ontdek onze app""",


"""Distance: %(distance)s km""": u"""Afstand: %(distance)s km""",


"""E-mail address""": u"""E-mailadres""",


"""eID data""": u"""eID data""",


"""email_reminder_cause_force_quitted""": u"""U hebt de %(app_name)s app volledig gesloten en sindsdien niet meer geopend. U hoeft de applicaties op uw telefoon niet volledig af te sluiten. Dit toch doen heeft geen invloed op de batterij van uw smartphone, en zorgt er voor dat wij u de berichten in de app niet kunnen bezorgen.""",


"""email_reminder_cause_no_internet""": u"""U hebt in de laatste 2 dagen geen internetconnectie kunnen maken met uw smartphone. Om dit op te lossen kan u terug verbinding maken met mobiel internet of een WiFi netwerk in de buurt.""",


"""email_reminder_cause_no_push""": u"""U hebt ervoor gekozen om geen pushmeldingen van de %(app_name)s app te ontvangen. Als u de pushmeldingen hebt geweigerd kunnen wij deze berichten niet bij u afleveren. U kan de pushmeldingen voor de app terug inschakelen via de instellingen van uw smartphone.""",


"""email_reminder_cause_uninstalled""": u"""U hebt de %(app_name)s app (per ongeluk) verwijderd. Als u de app hebt verwijderd, kan u deze terug installeren via de %(app_store)s of %(google_play)s en registreren als %(account)s. Als u de app verwijderd heeft en geen berichten meer wil ontvangen kan u zich uitschrijven onderaan deze mail.""",


"""email_reminder_intro""": u"""Het is ons opgevallen dat een aantal berichten in de %(app_name)s App u om de een of andere reden niet konden bereiken. Dit wil zeggen dat wij de berichten niet konden afleveren op uw toestel. Dit kan een aantal oorzaken hebben:""",


"""email_reminder_intro_no_mobile_html""": u"""Het is ons opgevallen dat u een aantal berichten heeft ontvangen in de %(app_name)s app. U kan deze berichten bekijken door de %(app_name)s app te installeren op uw smartphone en te registreren met uw e-mailadres. De %(app_name)s kan worden gedownload via de App Store of Google Play. Mocht u nog verdere vragen hebben kan u altijd contact opnemen met %(support)s of neem een kijkje op onze <a href=\"%(website_link)s\">website</a>.""",


"""email_reminder_intro_no_mobile_text""": u"""Het is ons opgevallen dat u een aantal berichten heeft ontvangen in de %(app_name)s app. U kan deze berichten bekijken door de %(app_name)s app te installeren op uw smartphone en te registreren met uw e-mailadres. De %(app_name)s kan worden gedownload via de App Store of Google Play. Mocht u nog verdere vragen hebben kan u altijd contact opnemen met %(support)s of neem een kijkje op onze website: %(website_link)s.""",


"""email_reminder_message_summary""": u"""Samenvatting berichten""",


"""email_reminder_outro_part1""": u"""Wij hopen dat via deze weg alle mogelijke problemen opgelost zijn en dat het ongemak tot een minimum is beperkt. Verder nog veel plezier met het gebruik van de %(app_name)s app!""",


"""email_reminder_outro_part2_html""": u"""Mocht u nog verdere vragen hebben kan u altijd contact opnemen met %(support)s of neem een kijkje op onze <a href=\"%(website_link)s\">website</a>.""",


"""email_reminder_outro_part2_text""": u"""Mocht u nog verdere vragen hebben kan u altijd contact opnemen met %(support)s of neem een kijkje op onze website: %(website_link)s.""",


"""email_reminder_unsubscribe_caption""": u"""Uitschrijven op \"%(notification_type)s\" van %(service)s""",


"""email_reminder_unsubscribe_from_email_html""": u"""Mocht u er toch voor kiezen om deze e-mail niet meer te ontvangen, kan u zich <a href=\"%(unsubscribe_link)s\">hier uitschrijven</a>.""",


"""email_reminder_unsubscribe_from_email_text""": u"""Mocht u er toch voor kiezen om deze e-mail niet meer te ontvangen, kan u zich uitschrijven via onderstaande link.""",


"""Enter your reply:""": u"""Voer uw antwoord in:""",


"""Error""": u"""Fout""",


"""Failed to unregister""": u"""Uitschrijven mislukt""",


"""Failed to upload the photo to %(service_name)s""": u"""Fout tijdens het uploaden van de foto naar %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Flow resultaat van %(user)s voor %(flow)s """,


"""http://www.ourcityapps.com""": u"""http://www.onzestadapp.be""",


"""Install %(other_app_name)s""": u"""Installeer %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Ongeldige hyperlink (%(url)s). De url moet bereikbaar zijn via http of https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""%(name)s uitnodigen op %(app_name)s""",


"""Invite %(name)s""": u"""%(name)s uitnodigen""",


"""Kind regards""": u"""Met vriendelijke groeten""",


"""Location: %(address)s""": u"""Locatie: %(address)s.""",


"""mdp_missing_address""": u"""Het adres dat opgeslagen is in uw MYDIGIPASS account is onvolledig. Gelieve je adres te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_eid_data""": u"""Er is geen eID data opgeslagen in uw MYDIGIPASS account. Gelieve je eID te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_email""": u"""Er is geen e-mailadres opgeslagen in uw MYDIGIPASS account. Gelieve je e-mailadres te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_phone""": u"""Er is geen telefoonnummer opgeslagen in uw MYDIGIPASS account. Gelieve je telefoonnummer te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_profile""": u"""De personalia opgeslagen in uw MYDIGIPASS account zijn onvolledig. Gelieve je profiel te vervolledigen in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_scopes""": u"""Er ontbreken gegevens in uw MYDIGIPASS account. De volgende gegevens ontbreken: %(missing_data)s

Vervolledig uw MYDIGIPASS account en probeer het opnieuw.

Zorg er ook voor dat u de laatste versie van de \"MYDIGIPASS Authenticator for Mobile\" app heeft.""",


"""Merchants""": u"""Handelaars""",


"""My services""": u"""Mijn diensten""",


"""Nearby services""": u"""Diensten in je buurt""",


"""No matching service found""": u"""Geen resultaten gevonden.""",


"""No service found""": u"""Geen resultaten gevonden.""",


"""notify_service_location_tracking""": u"""%(service)s volgt jouw locatie tot %(until)s.""",


"""Phone number""": u"""Telefoonnummer""",


"""Please try again later.""": u"""Probeer het later opnieuw.""",


"""Profile""": u"""Profiel""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Locatie van %(name)s gevonden.

Nauwkeurigheid: %(accuracy)sm""",


"""Reply""": u"""Antwoorden""",


"""Save""": u"""Bewaren""",


"""Scan QR code to discover!""": u"""Scan QR code om te ontdekken!""",


"""Search results""": u"""Zoekresultaten""",


"""Send reply""": u"""Zend antwoord""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Dienst %(name)s wenst met jou te communiceren via %(app_name)s.""",


"""Services""": u"""Diensten""",


"""Show map""": u"""Toon kaart""",


"""Spaces are not allowed in an e-mail address""": u"""Spaties zijn niet toegestaan in een e-mail adres""",


"""Submit""": u"""Versturen""",


"""successfully_unsubscribed_broadcast_type""": u"""U bent met succes uitgeschreven op meldingen met type \"%(notification_type)s\" van %(service)s""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""De gescande QR-code wordt niet ondersteund door de %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">%(app_name)s support</a>""",


"""the_app_team""": u"""Het %(app_name)s Team""",


"""the_our_city_app_coach_email_address""": u"""coach@onzestadapp.be""",


"""the_our_city_app_coach_email_address_html""": u"""de <a href=\"mailto:%(email)s\">Onze Stad Coach</a>""",


"""the_our_city_app_team""": u"""Het Onze Stad App Team""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Er is geen e-mailadres geconfigureerd in je Facebook account. Gelieve gebruik te maken van de e-mailgebaseerde login.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Deze service wordt niet ondersteund door de %(current_app_name)s app. Installeer de %(other_app_name)s app.""",


"""Unsubscribe""": u"""Uitschrijven""",


"""User %(name)s has requested to share your location.""": u"""%(name)s heeft jou een verzoek gestuurd om jouw locatie te bepalen.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s wenst met jou te communiceren via %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""De locatie van %(name)s kon niet bepaald worden.""",


"""Which type of broadcasts do you wish to receive?""": u"""Welke types van notificaties wenst u te ontvangen?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""Waarom wenst u zich uit te schrijven voor deze e-mail?""",


"""You are already connected with %(name)s.""": u"""Je bent reeds geconnecteerd met %(name)s.""",


"""You are now unsubscribed.""": u"""U bent nu uitgeschreven.""",


"""You can not register with this e-mail address""": u"""U kan zich niet registreren met dit e-mail adres"""}


# ###########################################################################################

D["pt_BR"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s tem %(count)d novas mensagens para você""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s tem 1 nova mensagem para você""",


"""%(app_name)s mobile registration""": u"""Registro do %(app_name)s para dispositivo móvel""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s aceitou sua solicitação para compartilhar localização.
Informação mais recente:

Precisão: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s aceitou sua solicitação para compartilhar localização. Infelizmente, não é possível determinar a localização dele(a) neste momento.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s acrescentou uma nota pessoal:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s não aceitou sua solicitação para rastrear a localização dele(a).""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s não possui um dispositivo que seja compatível com o rastreamento da localização.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s convidou você para o aplicativo %(app_name)s!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s acaba de entrar no %(app_name)s, e encontramos você na sua lista de amigos do Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s acrescentou uma nota pessoal:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s recomenda que você se conecte a %(service_name)s no %(app_name)s.

Sobre %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s recomenda que você se conecte a %(service_name)s no %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Olá,

Acabamos de dar-lhe as boas-vindas à nossa empresa. 
Você sabia que também oferecemos nossos serviços através do aplicativo %(app_name)s?
Clique no botão \"Adicionar a esta aplicación\" para adicionar-nos na sua lista de serviços.

Atenciosamente,
%(service_name)s.""",


"""_enable_location_services_ios7""": u"""Para ativar os serviços de localização:
1. Saia do aplicativo %(app_name)s e vá para Configurações.
2. Toque em Privacidade > Serviços de Localização.
3. Procure %(app_name)s e mude o botão para ON.""",


"""_enable_location_services_ios8""": u"""Para ativar os serviços de localização:
1. Saia do aplicativo %(app_name)s e vá para Configurações.
2. Toque em Privacidade > Serviços de Localização.
3. Procure %(app_name)s, toque em %(app_name)s e configure o acesso à localização como 'Sempre'.""",


"""_friend_denied_location_services""": u"""%(name)s desabilitou os serviços de localização para o aplicativo %(app_name)s""",


"""_friendship_accepted""": u"""Olá %(name)s,
%(friend_name)s é agora um contato seu.""",


"""_friendship_established""": u"""Olá %(name)s,
Agora você é amigo de %(friend_name)s.""",


"""_friendship_request_failed""": u"""Olá %(name)s,
Ocorreu uma falha na sua solicitação para conectar-se com %(friend_name)s.
Pressione o botão \"convidar\" para convidar %(friend_name)s.""",


"""_invited_too_often""": u"""Olá %(name)s,
Você convidou %(friend_email)s 3 vezes.
Para prevenir spam, %(app_name)s não enviará mais convites.""",


"""_invited_too_often_this_week""": u"""Olá %(name)s,
Você já tinha convidado %(friend_email)s nesta semana.
Para prevenir spam, %(app_name)s não enviará mais convites.""",


"""_invited_yourself""": u"""Olá %(name)s,
Você tentou iniciar amizade com você mesmo.
Infelizmente, isso não é possível.""",


"""_invitee_was_already_friend""": u"""Olá %(name)s,
Você tentou convidar %(friend_email)s que já está na sua lista de amigos.""",


"""_location_services_denied""": u"""%(name)s solicitou sua localização, mas você desabilitou os serviços de localização para o aplicativo %(app_name)s.""",


"""_unsupported_attachment_file_type""": u"""Formato de arquivo não compatível para o anexo %(url)s
Somente arquivos em formato pdf, jpeg e png são compatíveis.""",


"""_welcome_msg""": u"""Bem-vindo ao aplicativo %(app_name)s!

Conecte-se com seus prestadores de serviços favoritos, associações, instituições de assistência, amigos e comece a se comunicar.

Boas mensagens!

Observação: Se deseja participar do aplicativo %(app_name)s, entre em contato com %(contact_email_address)s""",


"""Accept invitation""": u"""Aceitar convite""",


"""Add to my services""": u"""Adicionar a esta aplicación""",


"""Associations""": u"""Associações""",


"""Cancel""": u"""Cancelar""",


"""Care""": u"""Assistência """,


"""Community Services""": u"""Serviços para a comunidade""",


"""Could not determine file type for attachment %(url)s""": u"""Não foi possível determinar o formato de arquivo do anexo %(url)s""",


"""Could not download attachment %(url)s""": u"""Não foi possível fazer download do anexo %(url)s""",


"""Decline invitation""": u"""Recusar convite""",


"""Discover our new app""": u"""Encontrar nosso aplicativo""",


"""Distance: %(distance)s km""": u"""Distância: %(distance)s km""",


"""E-mail address""": u"""Endereço de e-mail""",


"""Enter your reply:""": u"""Inserir sua resposta:""",


"""Error""": u"""Erro""",


"""Failed to upload the photo to %(service_name)s""": u"""Falha ao fazer upload da foto para %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Resultado do fluxo de %(user)s para %(flow)s""",


"""Install %(other_app_name)s""": u"""Instalar %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hyperlink (%(url)s) inválido. Deve ser acessível com http ou https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Convidar %(name)s para se conectar a %(app_name)s""",


"""Invite %(name)s""": u"""Convidar %(name)s""",


"""Location: %(address)s""": u"""Localização: %(address)s.""",


"""Merchants""": u"""Comerciantes""",


"""My services""": u"""Meus serviços""",


"""Nearby services""": u"""Serviços próximos""",


"""No matching service found""": u"""Nenhum serviço correspondente encontrado.""",


"""No service found""": u"""Nenhum serviço encontrado.""",


"""notify_service_location_tracking""": u"""%(service)s está rastreando sua localização até %(until)s.""",


"""Phone number""": u"""Número de telefone""",


"""Please try again later.""": u"""Tente novamente mais tarde.""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Localização de %(name)s recebida.

Precisão: %(accuracy)sm""",


"""Reply""": u"""Resposta""",


"""Save""": u"""Salvar""",


"""Scan QR code to discover!""": u"""Escaneie o código QR para descobrir!""",


"""Search results""": u"""Resultados da pesquisa""",


"""Send reply""": u"""Enviar resposta""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""O serviço de %(name)s quer entrar em contato com você através do %(app_name)s.""",


"""Services""": u"""Serviços""",


"""Show map""": u"""Mostrar mapa""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""O código QR escaneado não é compatível com o aplicativo %(app_name)s """,


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Não há um endereço de e-mail configurado na sua conta do Facebook. Use o e-mail para fazer o login.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Este serviço não é compatível com o aplicativo %(current_app_name)s. Instale o aplicativo %(other_app_name)s.""",


"""User %(name)s has requested to share your location.""": u"""O usuário %(name)s solicitou que você compartilhe sua localização.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s deseja entrar em contato com você pelo  %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""Não conseguimos determinar a localização de %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Que tipo de programação deseja receber?""",


"""You are already connected with %(name)s.""": u"""Você já está conectado com %(name)s.""",


"""You can not register with this e-mail address""": u"""Você não pode se registrar com esse endereço de e-mail"""}


# ###########################################################################################

D["ro"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s are %(count)d mesaje noi pentru tine""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s are 1 mesaj nou pentru tine""",


"""%(app_name)s mobile registration""": u"""Inregistrare mobila a %(app_name)s """,


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s a acceptat cererea pentru determinarea locatiei.
Cele mai recente informatii:

Acuratete: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s a acceptat cererea pentru determinarea locatiei. Din pacate, nu am putut stabili locatia in acest moment.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s a adaugat un mesaj personal:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s a refuzat cererea de fi localizati.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s nu detin un dispozitiv care permite localizarea.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s te invita in aplicatia  %(app_name)s !""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s tocmai s-a alaturat %(app_name)s, si v-am gasit in lista lui de prieteni de pe Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s a adaugat un mesaj personal:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s vă recomandă să vă conectați la %(service_name)s in %(app_name)s.

Despre %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s vă recomandă să vă conectați la %(service_name)s in %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Buna ziua,
Bine ati venit la firma noastra.
Stiati ca va putem oferii, de asemenea, serviciile noastre prin intermediul aplicatiei %(app_name)s ? 
Dati clic pe butonul \"Adauga la această aplicație\" pentru a ne adauga in lista dvs. de servicii. 
Cu stima, %(service_name)s.""",


"""_enable_location_services_ios7""": u"""Pentru a activa serviciile de localizare:
1. Parasiti aplicatia %(app_name)s si accesati aplicatia Configurări.
2. Tap Intimitate  > Servicii de localizare
3. Cauta %(app_name)s si schimba comutatorul pe ON""",


"""_enable_location_services_ios8""": u"""Pentru a activa serviciile de localizare:
1. Parasiti aplicatia %(app_name)s si accesati aplicatia Configurări.
2. Tap Intimitate  > Servicii de localizare
3. Cauta %(app_name)s si schimba accesarea localizării la 'Întotdeauna'""",


"""_friend_denied_location_services""": u"""%(name)s a dezactivat serviciile de localizare pentru aplicația %(app_name)s""",


"""_friendship_accepted""": u"""Buna %(name)s,
%(friend_name)s este acum conectat la tine.""",


"""_friendship_established""": u"""Buna %(name)s,
Ati devenit prieten cu %(friend_name)s.""",


"""_friendship_request_failed""": u"""Buna %(name)s,
Cererea de conexiune cu %(friend_name)s a esuat.
Apasati butonul de invita pentru a-l invita pe %(friend_name)s.""",


"""_invited_too_often""": u"""Buna %(name)s,
L-ati invitat pe %(friend_email)s de 3 ori.
Pentru a prevenii spam-ul, %(app_name)s nu va mai trimite nici o invitatie.""",


"""_invited_too_often_this_week""": u"""Buna %(name)s,
Deja l-ati invitat pe %(friend_email)s in aceasta saptamana.
Pentru a prevenii spam-ul, %(app_name)s nu va mai trimite nici o invitatie.""",


"""_invited_yourself""": u"""Buna %(name)s,
Ati incercat sa devii prieten cu tine insuti, din pacate acest lucru nu este posibil.""",


"""_invitee_was_already_friend""": u"""Buna %(name)s,
Ati incercat sa il invitati pe %(friend_email)s care este deja in lista dvs. de prieteni.""",


"""_location_services_denied""": u"""%(name)s solicitat locația dvs. dar servicii de localizare sunt dezactivate pentru aplicația %(app_name)s.""",


"""_unsupported_attachment_file_type""": u"""Tip de fişier neacceptat pentru ataşarea %(url)s
Suntem acceptă numai fişiere pdf, jpeg şi png""",


"""_welcome_msg""": u"""Bine ati venit la %(app_name)s!

Incepeti trimiterea de mesaje prietenilor tai de acum. Adaugati butoane de raspuns cu un singur clic pentru a obtine raspunsuri ultra-rapide!

Conversatie placuta!

PS: Dacă doriți să participați la %(app_name)s aplicația, contacte %(contact_email_address)s""",


"""Accept invitation""": u"""Accepta invitatia""",


"""Add to my services""": u"""Adauga la această aplicație""",


"""Address""": u"""Adresa""",


"""An unknown error has occurred""": u"""A aparut o eroare necunoscuta""",


"""Associations""": u"""Asociatii""",


"""Can not connect to server""": u"""Nu se poate conecta la server""",


"""Cancel""": u"""Anuleaza""",


"""Care""": u"""Ingrijire""",


"""Community Services""": u"""Servicii comunitare""",


"""Could not determine file type for attachment %(url)s""": u"""Nu a putut determina tipul de fișier pentru atașare %(url)s""",


"""Could not download attachment %(url)s""": u"""Nu poate descărca ataşament %(url)s""",


"""Decline invitation""": u"""Invitatie refuzata""",


"""Discover our new app""": u"""Descopera noua noastra aplicatie""",


"""Distance: %(distance)s km""": u"""Distanta: %(distance)s km""",


"""E-mail address""": u"""Adresa de e-mail""",


"""Enter your reply:""": u"""Introduceti raspunsul dvs:""",


"""Error""": u"""Eroare""",


"""Failed to unregister""": u"""Nu a reusit sa se retraga""",


"""Failed to upload the photo to %(service_name)s""": u"""Eroare la incarcarea pozei in %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Rezultatul flow-ului de %(user)s pentru %(flow)s""",


"""Install %(other_app_name)s""": u"""Instaleaza %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hyperlink invalid (%(url)s). Acesta trebuie să fie accesibil pe http sau https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Invita %(name)s pentru a se conecta la %(app_name)s""",


"""Invite %(name)s""": u"""Invita pe %(name)s""",


"""Location: %(address)s""": u"""Locatia: %(address)s.""",


"""Merchants""": u"""Comercianti""",


"""My services""": u"""Serviciile mele""",


"""Nearby services""": u"""Servicii din apropiere""",


"""No matching service found""": u"""Nu s-a gasit nici un serviciu care sa se potriveasca.""",


"""No service found""": u"""Nu există rezultate""",


"""notify_service_location_tracking""": u"""%(service)s urmărește locația dvs. până %(until)s.""",


"""Phone number""": u"""Numar de telefon""",


"""Please try again later.""": u"""Va rugam sa incercati din nou mai tarziu.""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Locatia primita a %(name)s.

Acuratete: %(accuracy)sm""",


"""Reply""": u"""Raspuns""",


"""Save""": u"""Salveaza""",


"""Scan QR code to discover!""": u"""Scanati codul QR pentru a descoperi!""",


"""Search results""": u"""Rezultatele cautarii""",


"""Send reply""": u"""Trimite un raspuns""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Serviciul %(name)s vrea sa se conecteze la tine prin %(app_name)s.""",


"""Services""": u"""Servicii""",


"""Show map""": u"""Arata harta""",


"""Submit""": u"""Trimite""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""Codul QR scanat nu este suportat de %(app_name)s app""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Nu există nici o adresă de e-mail configurată în contul dvs. de Facebook. Va rugam sa folositi metoda de conectare prin e-mail.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Acest serviciu nu este suportat de aplicatia %(current_app_name)s app. Va rugam instalati aplicatia %(other_app_name)s.""",


"""User %(name)s has requested to share your location.""": u"""Utilizatorul %(name)s a solicitat dezvaluirea locatiei dumneavoastra.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s vrea sa intre in contact cu tine prin %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""Nu am putut identifica locatia %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Ce tip de notificari doriti sa primiti?""",


"""You are already connected with %(name)s.""": u"""Sunteti deja conectat cu %(name)s.""",


"""You are now unsubscribed.""": u"""Sunteți acum dezabonat.""",


"""You can not register with this e-mail address""": u"""Nu va puteți înregistra cu această adresă de e-mail"""}



# Keep this line at the bottom
SUPPORTED_LANGUAGES = D.keys()
